<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('tbl_mahasiswas', function (Blueprint $table) {
            $table->id();
            $table->string('nim');
            $table->string('nama');
            $table->string('tpt_lahir');
            $table->string('tgl_lahir');
            $table->string('jk');
            $table->string('id_agama');
            $table->string('id_stskawin');
            $table->string('sts_kerja');
            $table->string('gol_darah');
            $table->string('sts_wni');
            $table->string('id_negara');
            $table->string('id_wilayah');
            $table->string('alamat');
            $table->string('kode_pos');
            $table->string('no_hp');
            $table->string('email_backup');
            $table->string('identitas_jenis');
            $table->string('identitas_nomor');
            $table->integer('id_jpdd');
            $table->string('sekolah_nama');
            $table->string('sekolah_alamat');
            $table->string('sekolah_jurusan');
            $table->string('sekolah_thntamat');
            $table->string('sekolah_nilai_skhun');
            $table->string('sekolah_no_skhun');
            $table->string('sekolah_nilai_ijazah');
            $table->string('sekolah_no_ijazah');
            $table->string('sekolah_nisn');
            $table->string('ayah_nama');
            $table->string('ayah_status');
            $table->string('ayah_tptlahir');
            $table->string('ayah_tgllahir');           
            $table->string('ayah_alamat');
            $table->string('ayah_kab');
            $table->string('ayah_kode_pos');
            $table->string('ayah_no_hp');
            $table->string('ayah_agama');
            $table->integer('ayah_idjpdd');
            $table->string('ayah_idpekerjaan');
            $table->string('ayah_ketpekerjaan');
            $table->string('ayah_idpenghasilan');
            $table->string('ayah_nik');
            $table->string('ibu_nama');
            $table->string('ibu_status');
            $table->string('ibu_alamat');
            $table->string('ibu_kode_pos');
            $table->string('ibu_no_hp');
            $table->string('ibu_kab');
            $table->string('ibu_tptlahir');
            $table->string('ibu_tgllahir');
            $table->string('ibu_agama');
            $table->integer('ibu_idjpdd');
            $table->string('ibu_idpekerjaan');
            $table->string('ibu_ketpekerjaan');
            $table->string('ibu_idpenghasilan');
            $table->string('ibu_nik');
            $table->string('wali_nama');
            $table->string('wali_no_pos');
            $table->string('wali_no_hp');
            $table->string('wali_tptlahir');
            $table->string('wali_tgllahir');
            $table->string('wali_agama');
            $table->integer('wali_idjpdd');
            $table->integer('wali_idpekerjaan');
            $table->string('wali_ketpekerjaan');
            $table->integer('wali_idpenghasilan');
            $table->string('wali_nik');
            $table->string('wali_alamat');
            $table->string('hubungan_wali');
            $table->string('id_pembayar_kuliah');
            $table->integer('id_prodi');
            $table->string('tgl_terdaftar');
            $table->string('ta_masuk');
            $table->string('ta_berakhir');
            $table->string('sts_mahasiswa');
            $table->string('id_jalurmasuk');
            $table->string('kode_pt_asal');
            $table->string('nm_pt_asal');
            $table->string('kode_prodi_asal');
            $table->string('nm_prodi_asal');
            $table->string('id_jenjang_asal');
            $table->string('nim_asal');
            $table->string('id_kurikulum');
            $table->integer('id_spp');
            $table->string('user_modified_spp');
            $table->string('date_modified_spp');
            $table->string('id_keluar');
            $table->string('status_perkuliahan');
            $table->string('photo');
            $table->string('status_registrasi');
            $table->string('user_registrasi');
            $table->string('date_registrasi');
            $table->string('no_invoice');
            $table->string('nominal_spp');
            $table->string('id_dosen_wali');
            $table->string('id_link_pmb');
            $table->string('password');
            $table->string('user_created');
            $table->string('date_created');
            $table->string('user_modified');
            $table->string('date_modified');
            $table->string('set_ip_ipk');
            $table->string('id_pd');
            $table->string('id_reg_pd');
            $table->string('status_feeder');
            $table->string('keterangan_error');
            $table->string('date_sync');
            $table->string('user_sync');
            $table->string('email');
            $table->string('selesai_sidang');
            $table->string('is_vvip');
            $table->string('npwp');
            $table->string('dusun');
            $table->string('rt');
            $table->string('rw');
            $table->string('id_jns_tinggal');
            $table->string('id_alat_transportasi');
            $table->string('penerima_kps');
            $table->string('nomor_kps');
            $table->string('id_semester_masuk');
            $table->string('jenis_roster');
            $table->string('sts_approve_jenis_roster');
            $table->string('lampiran_roster');
            $table->string('ukuran_baju');
            $table->string('is_boleh_perbaiki_biodata');
            $table->string('id_desa');
            $table->string('tgl_perbaiki_biodata');
            $table->string('id_manual');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('tbl_mahasiswas');
    }
};
