<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class tbl_mahasiswa extends Model
{
 use HasFactory;

    protected $fillable=[
        'nim',
        'nama',
        'tpt_lahir',
        'tgl_lahir',
        'jk',
        'id_agama',
        'id_stskawin',
        'sts_kerja',
        'gol_darah',
        'sts_wni',
        'id_negara',
        'id_wilayah',
        'alamat',
        'kode_pos',
        'no_hp',
        'email_backup',
        'identitas_jenis',
        'identitas_nomor',
        'id_agama',
        'id_jpdd',
        'sekolah_nama',
        'sekolah_alamat',
  'sekolah_jurusan',
  'sekolah_thntamat',
  'sekolah_nilai_skhun',
  'sekolah_no_skhun',
  'sekolah_nilai_ijazah',
  'sekolah_no_ijazah',
  'sekolah_nisn',
  'ayah_nama',
  'ayah_status'   ,
  'ayah_tptlahir',
  'ayah_tgllahir',
  'ayah_alamat',
  'ayah_kab',
  'ayah_kode_pos',
  'ayah_no_hp'  ,
  'ayah_agama',
  'ayah_idjpdd' ,
  'ayah_idpekerjaan' ,
  'ayah_ketpekerjaan',
  'ayah_idpenghasilan' ,
  'ayah_nik',
  'ibu_nama' ,
  'ibu_status',
  'ibu_alamat',
  'ibu_kode_pos',
  'ibu_no_hp' ,
  'ibu_kab' ,
  'ibu_tptlahir',
  'ibu_tgllahir',
  'ibu_agama',
  'ibu_idjpdd' ,
  'ibu_idpekerjaan' ,
  'ibu_ketpekerjaan',
  'ibu_idpenghasilan' ,
  'ibu_nik',
  'wali_nama' ,
  'wali_no_pos' ,
  'wali_no_hp' ,
  'wali_tptlahir' ,
  'wali_tgllahir',
  'wali_agama',
  'wali_idjpdd' ,
  'wali_idpekerjaan' ,
  'wali_ketpekerjaan',
  'wali_idpenghasilan' ,
  'wali_nik' ,
  'wali_alamat'  ,
  'hubungan_wali'  ,
  'id_pembayar_kuliah',
  'id_prodi' ,
  'tgl_terdaftar',
  'ta_masuk',
  'ta_berakhir',
  'sts_mahasiswa',
  'id_jalurmasuk',
  'kode_pt_asal' ,
  'nm_pt_asal',
  'kode_prodi_asal',
  'nm_prodi_asal',
  'id_jenjang_asal',
  'nim_asal' ,
  'id_kurikulum' ,
  'id_spp' ,
  'user_modified_spp',
  'date_modified_spp',
  'id_keluar',
  'status_perkuliahan',
  'photo',
  'status_registrasi' ,
  'user_registrasi',
  'date_registrasi',
  'no_invoice' ,
  'nominal_spp' ,
  'id_dosen_wali'  ,
  'id_link_pmb' ,
  'password',
  'user_created' ,
  'date_created'  ,
  'user_modified' ,
  'date_modified'  ,
  'set_ip_ipk',
  'id_pd',
  'id_reg_pd',
  'status_feeder',
  'keterangan_error',
  'date_sync'  ,
  'user_sync' ,
  'email' ,
  'selesai_sidang',
  'is_vvip',
  'npwp' ,
  'dusun',
  'rt' , 
  'rw' ,
  'id_jns_tinggal',
  'id_alat_transportasi',
  'penerima_kps' ,
  'nomor_kps' ,
  'id_semester_masuk' ,
  'jenis_roster',
  'sts_approve_jenis_roster',
  'lampiran_roster',
  'ukuran_baju' ,
  'is_boleh_perbaiki_biodat',
  'id_desa',
  'tgl_perbaiki_biodata'
];

}
